name: Test GITHUB_TOKEN

on:
  push:
    branches: [ "main" ]

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check GITHUB_TOKEN
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "GITHUB_TOKEN is not set"
            exit 1
          else
            echo "GITHUB_TOKEN is available"
          fi
