name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check GITHUB_TOKEN availability
      run: |
        if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
          echo "GITHUB_TOKEN is not set"
          exit 1
        else
          echo "GITHUB_TOKEN is available"
        fi

    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    

    - name: Super-linter
      uses: super-linter/super-linter@v7.2.1
      env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          LINTER_RULES_PATH: ./
          JAVA_FILE_NAME: google_checks_custom.xml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    - name: docker compose image
      run: docker compose up -d
  
    - name: Clean and Build with Maven
      run: mvn clean package --file pom.xml
      

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
