name: Java CI with Maven and Docker Integration Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check GITHUB_TOKEN availability
      run: |
        if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
          echo "GITHUB_TOKEN is not set"
          exit 1
        else
          echo "GITHUB_TOKEN is available"
        fi

    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Run with Docker Compose
      run: |
        docker compose up --build -d
        echo "Waiting for services to stabilize..."
        sleep 15
        docker compose ps

    # Integration Test: Call the REST API from the frontend or backend directly
    - name: Integration Test - REST API Health Check
      run: |
        echo "Running Integration Test..."
        sleep 10  # Wait for services to be fully ready
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8081/api/calculator/sum?num1=4&num2=5)
        
        if [ "$RESPONSE" -eq 200 ]; then
          echo "Integration Test Passed"
        else
          echo "Integration Test Failed with status $RESPONSE"
          exit 1
        fi


    - name: Tear Down Docker Containers
      if: always()
      run: docker compose down
